# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configWindowUI.ui'
#
# Created: Tue Mar  4 12:56:24 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8

    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_Config(object):
    def setupUi(self, Config):
        Config.setObjectName(_fromUtf8("Config"))
        Config.resize(511, 271)
        self.layoutWidget = QtGui.QWidget(Config)
        self.layoutWidget.setGeometry(QtCore.QRect(150, 20, 239, 32))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.splitter = QtGui.QSplitter(Config)
        self.splitter.setGeometry(QtCore.QRect(10, 70, 501, 104))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.layoutWidget2 = QtGui.QWidget(self.splitter)
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.colorThresholdVal = QtGui.QSlider(self.layoutWidget2)
        self.colorThresholdVal.setMaximum(300)
        self.colorThresholdVal.setOrientation(QtCore.Qt.Horizontal)
        self.colorThresholdVal.setObjectName(_fromUtf8("colorThresholdVal"))
        self.verticalLayout_2.addWidget(self.colorThresholdVal)
        self.p1 = QtGui.QSlider(self.layoutWidget2)
        self.p1.setMaximum(300)
        self.p1.setOrientation(QtCore.Qt.Horizontal)
        self.p1.setObjectName(_fromUtf8("p1"))
        self.verticalLayout_2.addWidget(self.p1)
        self.p2 = QtGui.QSlider(self.layoutWidget2)
        self.p2.setMaximum(300)
        self.p2.setOrientation(QtCore.Qt.Horizontal)
        self.p2.setObjectName(_fromUtf8("p2"))
        self.verticalLayout_2.addWidget(self.p2)
        self.layoutWidget3 = QtGui.QWidget(self.splitter)
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.spinBox = QtGui.QSpinBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.spinBox.setFont(font)
        self.spinBox.setMaximum(2000)
        self.spinBox.setSingleStep(10)
        self.spinBox.setProperty("value", 400)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.verticalLayout_3.addWidget(self.spinBox)
        self.spinBox_2 = QtGui.QSpinBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setMaximum(2000)
        self.spinBox_2.setSingleStep(10)
        self.spinBox_2.setProperty("value", 400)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.verticalLayout_3.addWidget(self.spinBox_2)
        self.spinBox_3 = QtGui.QSpinBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setMaximum(2000)
        self.spinBox_3.setSingleStep(10)
        self.spinBox_3.setProperty("value", 400)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.verticalLayout_3.addWidget(self.spinBox_3)
        self.layoutWidget4 = QtGui.QWidget(Config)
        self.layoutWidget4.setGeometry(QtCore.QRect(160, 180, 173, 74))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.leftButton = QtGui.QPushButton(self.layoutWidget4)
        self.leftButton.setObjectName(_fromUtf8("leftButton"))
        self.horizontalLayout.addWidget(self.leftButton)
        self.rightButton = QtGui.QPushButton(self.layoutWidget4)
        self.rightButton.setObjectName(_fromUtf8("rightButton"))
        self.horizontalLayout.addWidget(self.rightButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.buttonBox = QtGui.QDialogButtonBox(self.layoutWidget4)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel | QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_4.addWidget(self.buttonBox)

        self.retranslateUi(Config)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Config.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Config.reject)
        QtCore.QObject.connect(self.colorThresholdVal, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")),
                               self.spinBox.setValue)
        QtCore.QObject.connect(self.spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")),
                               self.colorThresholdVal.setValue)
        QtCore.QObject.connect(self.p1, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_2.setValue)
        QtCore.QObject.connect(self.spinBox_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.p1.setValue)
        QtCore.QObject.connect(self.p2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_3.setValue)
        QtCore.QObject.connect(self.spinBox_3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.p2.setValue)
        QtCore.QMetaObject.connectSlotsByName(Config)

    def retranslateUi(self, Config):
        Config.setWindowTitle(_translate("Config", "Config", None))
        self.label.setText(_translate("Config", "IP:", None))
        self.lineEdit.setText(_translate("Config", "192.168.1.1", None))
        self.label_2.setText(_translate("Config", "Color threshold:", None))
        self.label_3.setText(_translate("Config", "Edge param 1: ", None))
        self.label_4.setText(_translate("Config", "Edge param 2: ", None))
        self.leftButton.setText(_translate("Config", "Rotate left", None))
        self.rightButton.setText(_translate("Config", "Rotate right", None))

