# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configWindowUI.ui'
#
# Created: Mon Mar 03 21:47:31 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Config(object):
    def setupUi(self, Config):
        Config.setObjectName(_fromUtf8("Config"))
        Config.resize(511, 218)
        self.buttonBox = QtGui.QDialogButtonBox(Config)
        self.buttonBox.setGeometry(QtCore.QRect(-10, 180, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.widget = QtGui.QWidget(Config)
        self.widget.setGeometry(QtCore.QRect(150, 20, 239, 31))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.splitter = QtGui.QSplitter(Config)
        self.splitter.setGeometry(QtCore.QRect(10, 70, 501, 104))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.widget1 = QtGui.QWidget(self.splitter)
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.widget2 = QtGui.QWidget(self.splitter)
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.colorThresholdVal = QtGui.QSlider(self.widget2)
        self.colorThresholdVal.setMaximum(300)
        self.colorThresholdVal.setOrientation(QtCore.Qt.Horizontal)
        self.colorThresholdVal.setObjectName(_fromUtf8("colorThresholdVal"))
        self.verticalLayout_2.addWidget(self.colorThresholdVal)
        self.p1 = QtGui.QSlider(self.widget2)
        self.p1.setMaximum(300)
        self.p1.setOrientation(QtCore.Qt.Horizontal)
        self.p1.setObjectName(_fromUtf8("p1"))
        self.verticalLayout_2.addWidget(self.p1)
        self.p2 = QtGui.QSlider(self.widget2)
        self.p2.setMaximum(300)
        self.p2.setOrientation(QtCore.Qt.Horizontal)
        self.p2.setObjectName(_fromUtf8("p2"))
        self.verticalLayout_2.addWidget(self.p2)
        self.widget3 = QtGui.QWidget(self.splitter)
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.spinBox = QtGui.QSpinBox(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.spinBox.setFont(font)
        self.spinBox.setMaximum(2000)
        self.spinBox.setSingleStep(10)
        self.spinBox.setProperty("value", 400)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.verticalLayout_3.addWidget(self.spinBox)
        self.spinBox_2 = QtGui.QSpinBox(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setMaximum(2000)
        self.spinBox_2.setSingleStep(10)
        self.spinBox_2.setProperty("value", 400)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.verticalLayout_3.addWidget(self.spinBox_2)
        self.spinBox_3 = QtGui.QSpinBox(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setMaximum(2000)
        self.spinBox_3.setSingleStep(10)
        self.spinBox_3.setProperty("value", 400)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.verticalLayout_3.addWidget(self.spinBox_3)

        self.retranslateUi(Config)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Config.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Config.reject)
        QtCore.QObject.connect(self.colorThresholdVal, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")),
                               self.spinBox.setValue)
        QtCore.QObject.connect(self.spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")),
                               self.colorThresholdVal.setValue)
        QtCore.QObject.connect(self.p1, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_2.setValue)
        QtCore.QObject.connect(self.spinBox_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.p1.setValue)
        QtCore.QObject.connect(self.p2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_3.setValue)
        QtCore.QObject.connect(self.spinBox_3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.p2.setValue)
        QtCore.QMetaObject.connectSlotsByName(Config)

    def retranslateUi(self, Config):
        Config.setWindowTitle(_translate("Config", "Config", None))
        self.label.setText(_translate("Config", "IP:", None))
        self.lineEdit.setText(_translate("Config", "192.168.1.1", None))
        self.label_2.setText(_translate("Config", "Color threshold:", None))
        self.label_3.setText(_translate("Config", "Edge param 1: ", None))
        self.label_4.setText(_translate("Config", "Edge param 2: ", None))

